sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t maxwellforever/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true maxwellforever/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker2'
  env: 'Docker2-env'
  bucket_name: 'elasticbeanstalk-us-east-1-671878845309'
  bucket_path: 'docker2'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
